version: '3'
services:
  rabbitMq:
    image: rabbitmq:alpine
    build: ./non-reactive
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - "5672:5672"
  # mysql:
  #   container_name: mysql-service
  #   image: mysql:latest
  #   hostname: localhost
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 12345678
  #     MYSQL_DATABASE: spring_jmeter
  #   volumes:
  #     - /Users/ridho/Documents/jmeter-test-result/db:/var/lib/mysql
  #   restart: unless-stopped